---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:ap-southeast-1:767397673785:generatedTemplate/6a2f017a-9305-4a23-8f79-c226b937e871"
Resources:

# CodeArtifact Upstream Repository
  CodeArtifactRepository00repositorynextworkmavencentralstore00FKKew:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      RepositoryName: "maven-central-store"
      Description: "Provides Maven artifacts from Maven Central Repository."
      ExternalConnections:
      - "public:maven-central"
      DomainName:
        Fn::GetAtt:
        - "CodeArtifactDomain00domainnextwork00jTvKV"
        - "Name"

  # CodeArtifact Domain
  CodeArtifactDomain00domainnextwork00jTvKV:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Domain"
    DeletionPolicy: "Delete"
    Properties:
      DomainName: "nextwork"

  # S3 Build Artifacts Bucket
  S3Bucket00nextworkbuildartifactsedmon00sqOvZ:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "nextwork-build-artifacts-edmon"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"

  # IAM Role for CodeBuild
  IAMRole00codebuildnextworkwebbuildservicerole00iqhee:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/service-role/"
      MaxSessionDuration: 3600
      RoleName: "codebuild-nextwork-web-build-service-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"

  # IAM Policy for CodeArtifact
  IAMManagedPolicy00policycodeartifactnextworkconsumerpolicy00gUUUU:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00iqhee"
    Properties:
      ManagedPolicyName: "codeartifact-nextwork-consumer-policy"
      Path: "/"
      Description: "Provides permissions to read from CodeArtifact."
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "*"
          Action:
          - "codeartifact:GetAuthorizationToken"
          - "codeartifact:GetRepositoryEndpoint"
          - "codeartifact:ReadFromRepository"
          Effect: "Allow"
        - Condition:
            StringEquals:
              sts:AWSServiceName: "codeartifact.amazonaws.com"
          Resource: "*"
          Action: "sts:GetServiceBearerToken"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []


  # IAM Policy for CodeBuild CloudWatch Logs
  IAMManagedPolicy00policyserviceroleCodeBuildCloudWatchLogsPolicynextworkwebbuildapsoutheast100tPolq:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00iqhee"
    Properties:
      ManagedPolicyName: "CodeBuildCloudWatchLogsPolicy-nextwork-web-build-ap-southeast-1"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:logs:ap-southeast-1:767397673785:log-group:nextwork-build-logs"
          - "arn:aws:logs:ap-southeast-1:767397673785:log-group:nextwork-build-logs:*"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []

  # IAM Policy for CodeArtifact
  CodeArtifactRepository00repositorynextworknextworkpackages00grd2B:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      Upstreams:
      - Fn::GetAtt:
        - "CodeArtifactRepository00repositorynextworkmavencentralstore00FKKew"
        - "Name"
      RepositoryName: "nextwork-packages"
      Description: "Packages for the NextWork web app."
      DomainName:
        Fn::GetAtt:
        - "CodeArtifactDomain00domainnextwork00jTvKV"
        - "Name"

  #IAM Base Policy for CodeBuild
  IAMManagedPolicy00policyserviceroleCodeBuildBasePolicynextworkwebbuildapsoutheast100xAU84:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00iqhee"
    Properties:
      ManagedPolicyName: "CodeBuildBasePolicy-nextwork-web-build-ap-southeast-1"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:logs:ap-southeast-1:767397673785:log-group:/aws/codebuild/nextwork-web-build"
          - "arn:aws:logs:ap-southeast-1:767397673785:log-group:/aws/codebuild/nextwork-web-build:*"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Effect: "Allow"
        - Resource:
          - "arn:aws:s3:::codepipeline-ap-southeast-1-*"
          Action:
          - "s3:PutObject"
          - "s3:GetObject"
          - "s3:GetObjectVersion"
          - "s3:GetBucketAcl"
          - "s3:GetBucketLocation"
          Effect: "Allow"
        - Resource:
          - "arn:aws:s3:::nextwork-build-artifacts-edmon"
          - "arn:aws:s3:::nextwork-build-artifacts-edmon/*"
          Action:
          - "s3:PutObject"
          - "s3:GetObject"
          - "s3:GetBucketAcl"
          - "s3:GetBucketLocation"
          - "s3:ListBucket"
          Effect: "Allow"
        - Resource:
          - "arn:aws:codebuild:ap-southeast-1:767397673785:report-group/nextwork-web-build-*"
          Action:
          - "codebuild:CreateReportGroup"
          - "codebuild:CreateReport"
          - "codebuild:UpdateReport"
          - "codebuild:BatchPutTestCases"
          - "codebuild:BatchPutCodeCoverages"
          Effect: "Allow"
      Roles:
      - "codebuild-nextwork-web-build-service-role"
      Users: []


  # CodeBuild Project
  CodeBuildProject:
    DependsOn: "IAMRole00codebuildnextworkwebbuildservicerole00iqhee"
    Type: AWS::CodeBuild::Project
    Properties:
      Name: nextwork-web-build
      Description: Build project for NextWork web application
      Source:
        Type: GITHUB
        Location: https://github.com/EdmonNextwork6/nextwork-devops-webappdeploy
        BuildSpec: buildspec.yml
      Artifacts:
        Type: S3
        Name: nextwork-web-build.zip
        Packaging: ZIP
        Location: !Ref S3Bucket00nextworkbuildartifactsedmon00sqOvZ
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:corretto8
      ServiceRole: !GetAtt IAMRole00codebuildnextworkwebbuildservicerole00iqhee.Arn
      LogsConfig:
        CloudWatchLogs:
          GroupName: nextwork-build-logs
          Status: ENABLED
          StreamName: webapp
